### ISSUE TITLE
I am getting the below error after connecting to wandb and using ./run.sh [path/to/config]

### ISSUE THREAD

**Issue by swapnik-iitkgp** [Erosinho13/FedDrive#3]
```GPUs in usage: 0
Running Centralized experiment with 828 epochs
Setting up distributed...
Let's use 1 GPUs!
Done
Initializing wandb...
wandb: Currently logged in as: swapnikvarala. Use `wandb login --relogin` to force relogin
Problem at: /usr/local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py 837 getcaller
Traceback (most recent call last):
  File "/content/FedDrive/src/run.py", line 31, in <module>
    run_experiment()
  File "/content/FedDrive/src/run.py", line 15, in run_experiment
    main(args)
  File "/content/FedDrive/src/centr_setting/main.py", line 17, in main
    writer, device, rank, world_size, logger, label2color, denorm = setup_env(args)
                                                                    ^^^^^^^^^^^^^^^
  File "/content/FedDrive/src/utils/utils.py", line 36, in setup_env
    logger = CustomWandbLogger(name=get_job_name(args), project=get_project_name(args.framework, args.dataset),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/FedDrive/src/utils/logger.py", line 7, in __init__
    super(CustomWandbLogger, self).__init__(name=name, project=project, group=group, entity=entity, offline=offline,
  File "/usr/local/lib/python3.11/site-packages/pytorch_lightning/loggers/wandb.py", line 358, in __init__
    _ = self.experiment
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lightning_fabric/loggers/logger.py", line 114, in experiment
    return fn(self)
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytorch_lightning/loggers/wandb.py", line 406, in experiment
    self._experiment = wandb.init(**self._wandb_init)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1173, in init
    raise e
  File "/usr/local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
          ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24118) of binary: /usr/local/bin/python3
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-18_17:50:12
  host      : f905eb7441a0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 24118)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================```

**Comment by hwan-sig** [comment]
I have same problem.
How to solve Wandb problem?

**Comment by Erosinho13** [comment]
Hi, thank you for your interest in our code. The error you reported depends on the wandb backend, not our code.
Please refer to the following link: https://community.wandb.ai/t/wandb-errors-commerror-run-initialization-has-timed-out-after-60-0-sec/4284

You can temporarily run your experiments setting the environmental variable WANDB_MODE as disabled by adding the following line of code at the beginning: `os.environ['WANDB_MODE'] = 'disabled'`

**Comment by kagHarsh** [comment]
I disabled wandb mode as you suggested above, still I am facing issues


RuntimeError: CUDA error: invalid device function
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 581611) of binary: /home/cvblhcs22/anaconda3/envs/feddrive/bin/python3
Traceback (most recent call last):
  File "/home/cvblhcs22/anaconda3/envs/feddrive/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cvblhcs22/anaconda3/envs/feddrive/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cvblhcs22/anaconda3/envs/feddrive/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/cvblhcs22/anaconda3/envs/feddrive/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/cvblhcs22/anaconda3/envs/feddrive/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/cvblhcs22/anaconda3/envs/feddrive/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/cvblhcs22/anaconda3/envs/feddrive/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/cvblhcs22/anaconda3/envs/feddrive/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-23_19:21:01
  host      : ubuntu-22-0-4
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 581611)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by kumarrah2002** [comment]
I also have the same issue as @kagHarsh above despite WandB working. How do I fix the issue of the local rank? I did all the instructions given in the README.
